version: "2"

services:
  CdcToKafka:
    image: "jackvanlightly/cdctools.cdctokafka:1.4"
    container_name: cdctools.cdctokafka
    environment:
      CDCTOOLS_IntervalMs: 5000
      CDCTOOLS_TableTopicPrefix: cdc-table-
      CDCTOOLS_Tables: Person,PersonAddress
      CDCTOOLS_Mode: cdc
      CDCTOOLS_SerializationMode: Avro
      CDCTOOLS_SendWithKey: false
      CDCTOOLS_PrintPercentProgressMod: 5
      CDCTOOLS_BatchSize: 1000
      CDCTOOLS_DatabaseConnection: Server=(local);Database=CdcToRedshift;Trusted_connection=true;
      CDCTOOLS_KafkaBootstrapServers: 192.168.1.1:9092
      CDCTOOLS_KafkaSchemaRegistryUrl: http://192.168.1.1:8081
  KafkaToRedshift:
    image: "jackvanlightly/cdctools.kafkatoredshift:1.4"
    container_name: cdctools.kafkatoredshift
    environment:
      CDCTOOLS_AccessKey: 12345
      CDCTOOLS_SecretAccessKey: 6789
      CDCTOOLS_RedshiftUser: rs_user
      CDCTOOLS_RedshiftPassword: abcde
      CDCTOOLS_RedshiftRole: arn:aws:iam::somenumbershere:role/rolenamehere
      CDCTOOLS_AwsRegion: eu-west-1
      CDCTOOLS_RedshiftServer: blahblah.redshift.amazonaws.com
      CDCTOOLS_RedshiftPort: 5439
      CDCTOOLS_RedshiftDbName: dev
      CDCTOOLS_S3BucketName: yourbucketname
      CDCTOOLS_WindowMs: 10000
      CDCTOOLS_WindowItems: 5000
      CDCTOOLS_TableTopicPrefix: cdc-table-
      CDCTOOLS_Tables: Person,PersonAddress
      CDCTOOLS_SerializationMode: Avro
      CDCTOOLS_MessagesHaveKey: false
      CDCTOOLS_KafkaBootstrapServers: 192.168.1.1:9092
      CDCTOOLS_KafkaSchemaRegistryUrl: http://192.168.1.1:8081
